service: postfix-error
logs:
  - /var/log/maillog
protocols:
  - all
ports:
  - all
rules:
  - DROP
regexes:
  - '/postfix\/smtpd\[.*\]: .* reject: RCPT from .*\[(.*)\]: 450 /'
  - '/postfix\/smtpd\[.*\]: .* reject: RCPT from .*\[(.*)\]: 554 /'
  - '/postfix\/smtpd\[.*\]: .* reject: VRFY from .*\[(.*)\]: 550 /'