process_name:
  postfix
watch_log_files:
  - /var/log/mail.log
protocols:
  - all
ports:
  - all
rules:
  - DROP
regexes:
  - '/^(?P<date>(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+[0-9]{1,2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}).*\[(?P<ip>.*)\]:\sSASL\sLOGIN\sauthentication\sfailed:\sauthentication\sfailure$/i'
effective_second:
  86400
filter_period_second:
  86400
filter_period_count:
  10